export const SITE = {
  name:        "TriAxon Technologies",
  tagline:     "We Build Digital Products That Scale & Perform",
  description:
    "Full-stack web, mobile, AI/ML, cloud, UI/UX, and digital marketing services for startups and enterprises worldwide.",
  url:         "https://triaxon.tech",
  logo:        "/logo.png",
  favicon:     "/favicon.ico",
  ogImage:     "/og-default.jpg",
  email:       "hello@triaxon.tech",
  salesEmail:  "sales@triaxon.tech",
  careersEmail:"careers@triaxon.tech",
  phone:       "+91 98765 43210",
  whatsapp:    "919876543210",
  foundedYear: 2016,
  locale:      "en_IN",
  timezone:    "Asia/Kolkata",
};

export const COLORS = {
  blue:         "#2B7EC1",
  blueDim:      "#1f5f94",
  blueGlow:     "rgba(43,126,193,0.18)",
  purple:       "#6B3FA0",
  purpleDim:    "#502d7a",
  purpleGlow:   "rgba(107,63,160,0.18)",
  teal:         "#00B4C8",
  tealDim:      "#0090a1",
  tealGlow:     "rgba(0,180,200,0.18)",
  dark900:      "#0D1117",
  dark800:      "#0A1628",
  dark700:      "#0D1F3C",
  textPrimary:  "#F4F6F9",
  textSecondary:"#9CA3AF",
  textMuted:    "#4A6080",
};

export const GRADIENTS = {
  brand:     "linear-gradient(135deg, #2B7EC1 0%, #6B3FA0 50%, #00B4C8 100%)",
  blueTeal:  "linear-gradient(135deg, #2B7EC1 0%, #00B4C8 100%)",
  purpleTeal:"linear-gradient(135deg, #6B3FA0 0%, #00B4C8 100%)",
  hero:      "linear-gradient(180deg, #0D1117 0%, #0A1628 100%)",
};

export const OFFICES = [
  {
    city:    "Indore (HQ)",
    country: "India",
    flag:    "🇮🇳",
    address: "4th Floor, Treasure Island Mall, MG Road, Indore – 452001, M.P.",
    phone:   "+91 98765 43210",
    email:   "hello@triaxon.tech",
    mapsUrl: "https://maps.google.com/?q=Treasure+Island+Mall+MG+Road+Indore",
    primary: true,
  },
  {
    city:    "Dubai (Sales)",
    country: "UAE",
    flag:    "🇦🇪",
    address: "DIFC, Gate Avenue, Dubai, UAE",
    phone:   "+971 50 000 0000",
    email:   "dubai@triaxon.tech",
    mapsUrl: "https://maps.google.com/?q=DIFC+Gate+Avenue+Dubai",
    primary: false,
  },
  {
    city:    "London (Sales)",
    country: "UK",
    flag:    "🇬🇧",
    address: "WeWork, 1 Poultry, London EC2R 8EJ, UK",
    phone:   "+44 20 0000 0000",
    email:   "london@triaxon.tech",
    mapsUrl: "https://maps.google.com/?q=1+Poultry+London",
    primary: false,
  },
];

export const NAV_LINKS = [
  { label: "Services",  href: "/services"  },
  { label: "Portfolio", href: "/portfolio" },
  { label: "About",     href: "/about"     },
  { label: "Blog",      href: "/blog"      },
  { label: "Careers",   href: "/careers"   },
];

export const NAV_SERVICES = [
  { label: "Full-Stack Web",    href: "/services/fullstack",         icon: "🌐" },
  { label: "Mobile App Dev",    href: "/services/app-development",   icon: "📱" },
  { label: "UI/UX Design",      href: "/services/ui-ux-design",      icon: "🎨" },
  { label: "Cloud & DevOps",    href: "/services/cloud-devops",      icon: "☁️" },
  { label: "AI & ML",           href: "/services/ai-ml",             icon: "🤖" },
  { label: "Digital Marketing", href: "/services/digital-marketing", icon: "📣" },
];

export const FOOTER_LINKS = {
  Services: [
    { label: "Web Development",   href: "/services/fullstack"         },
    { label: "Mobile Apps",       href: "/services/app-development"   },
    { label: "UI/UX Design",      href: "/services/ui-ux-design"      },
    { label: "Cloud & DevOps",    href: "/services/cloud-devops"      },
    { label: "AI & ML",           href: "/services/ai-ml"             },
    { label: "Digital Marketing", href: "/services/digital-marketing" },
  ],
  Company: [
    { label: "About Us",  href: "/about"     },
    { label: "Portfolio", href: "/portfolio" },
    { label: "Blog",      href: "/blog"      },
    { label: "Careers",   href: "/careers"   },
    { label: "Contact",   href: "/contact"   },
  ],
  Legal: [
    { label: "Privacy Policy",   href: "/privacy"    },
    { label: "Terms of Service", href: "/terms"       },
    { label: "Cookie Policy",    href: "/cookies"     },
    { label: "Sitemap",          href: "/sitemap.xml" },
  ],
};

export const SOCIAL_LINKS = [
  { label: "LinkedIn",    href: "https://linkedin.com/company/triaxon-tech", icon: "linkedin", handle: "triaxon-tech"  },
  { label: "Twitter / X", href: "https://twitter.com/triaxontech",           icon: "twitter",  handle: "@triaxontech" },
  { label: "GitHub",      href: "https://github.com/triaxon-tech",           icon: "github",   handle: "triaxon-tech"  },
  { label: "Instagram",   href: "https://instagram.com/triaxontech",         icon: "instagram",handle: "@triaxontech" },
  { label: "YouTube",     href: "https://youtube.com/@triaxontech",          icon: "youtube",  handle: "@triaxontech" },
];

// ─── SERVICES (used on /services page grid + ServiceCard) ────────────────────
// iconName maps to the iconMap object inside ServiceCard.jsx
// accentBg / accentBorder are pre-computed so the card never does string math
export const SERVICES = [
  {
    id:           "fullstack",
    slug:         "fullstack",
    href:         "/services/fullstack",
    iconName:     "code",                        // ← matches iconMap key in ServiceCard
    emoji:        "🌐",
    title:        "Full-Stack Web Development",
    shortTitle:   "Web Dev",
    tagline:      "Next.js · Node.js · PostgreSQL",
    description:  "High-performance web applications engineered for scale. From MVPs to enterprise SaaS — built to grow with you from day one.",
    badge:        "Most Popular",
    badgeVariant: "blue",
    accent:       "#2B7EC1",
    accentBg:     "rgba(43,126,193,0.08)",
    accentBorder: "rgba(43,126,193,0.25)",
    stat:         "150+ apps launched",
    tags:         ["Next.js", "React", "Node.js", "TypeScript", "PostgreSQL"],
    featured:     true,
  },
  {
    id:           "app-development",
    slug:         "app-development",
    href:         "/services/app-development",
    iconName:     "mobile",
    emoji:        "📱",
    title:        "Mobile App Development",
    shortTitle:   "Mobile",
    tagline:      "Flutter · React Native · Swift",
    description:  "Native-quality iOS and Android apps users love. 4.8★ average rating across 30+ apps launched on both stores worldwide.",
    badge:        null,
    badgeVariant: null,
    accent:       "#6B3FA0",
    accentBg:     "rgba(107,63,160,0.08)",
    accentBorder: "rgba(107,63,160,0.25)",
    stat:         "30+ apps shipped",
    tags:         ["Flutter", "React Native", "Swift", "Kotlin", "Firebase"],
    featured:     true,
  },
  {
    id:           "ui-ux-design",
    slug:         "ui-ux-design",
    href:         "/services/ui-ux-design",
    iconName:     "design",
    emoji:        "🎨",
    title:        "UI/UX Design",
    shortTitle:   "Design",
    tagline:      "Figma · Design Systems · Prototypes",
    description:  "User-centred interfaces that convert. We design for delight, accessibility, and business outcomes — not just aesthetics.",
    badge:        null,
    badgeVariant: null,
    accent:       "#00B4C8",
    accentBg:     "rgba(0,180,200,0.08)",
    accentBorder: "rgba(0,180,200,0.25)",
    stat:         "98% client satisfaction",
    tags:         ["Figma", "Design Systems", "Prototyping", "User Research"],
    featured:     true,
  },
  {
    id:           "cloud-devops",
    slug:         "cloud-devops",
    href:         "/services/cloud-devops",
    iconName:     "cloud",
    emoji:        "☁️",
    title:        "Cloud & DevOps",
    shortTitle:   "Cloud",
    tagline:      "AWS · Docker · Kubernetes",
    description:  "Reliable, auto-scaling infrastructure with zero-downtime deployments. We architect for the traffic you'll have tomorrow.",
    badge:        null,
    badgeVariant: null,
    accent:       "#2B7EC1",
    accentBg:     "rgba(43,126,193,0.08)",
    accentBorder: "rgba(43,126,193,0.25)",
    stat:         "99.99% uptime SLA",
    tags:         ["AWS", "GCP", "Docker", "Kubernetes", "Terraform", "CI/CD"],
    featured:     false,
  },
  {
    id:           "ai-ml",
    slug:         "ai-ml",
    href:         "/services/ai-ml",
    iconName:     "ai",
    emoji:        "🤖",
    title:        "AI & Machine Learning",
    shortTitle:   "AI/ML",
    tagline:      "LLMs · RAG · ML Pipelines",
    description:  "Add real intelligence to your product. LLM integrations, recommendation engines, and custom ML models deployed to production.",
    badge:        "Trending",
    badgeVariant: "purple",
    accent:       "#6B3FA0",
    accentBg:     "rgba(107,63,160,0.08)",
    accentBorder: "rgba(107,63,160,0.25)",
    stat:         "50+ AI models deployed",
    tags:         ["OpenAI", "LangChain", "PyTorch", "Pinecone", "FastAPI"],
    featured:     true,
  },
  {
    id:           "digital-marketing",
    slug:         "digital-marketing",
    href:         "/services/digital-marketing",
    iconName:     "marketing",
    emoji:        "📣",
    title:        "Digital Marketing",
    shortTitle:   "Marketing",
    tagline:      "SEO · Paid Ads · Growth",
    description:  "Data-driven growth marketing that fills your pipeline. SEO, paid media, and conversion optimisation all under one roof.",
    badge:        null,
    badgeVariant: null,
    accent:       "#00B4C8",
    accentBg:     "rgba(0,180,200,0.08)",
    accentBorder: "rgba(0,180,200,0.25)",
    stat:         "3.2x avg. ROAS",
    tags:         ["SEO", "Google Ads", "Meta Ads", "Content", "Analytics"],
    featured:     false,
  },
];

export const STATS = [
  { value: 150, suffix: "+", label: "Projects Delivered",  icon: "🚀" },
  { value: 50,  suffix: "+", label: "Happy Clients",       icon: "🌍" },
  { value: 8,   suffix: "+", label: "Years Experience",    icon: "⚡" },
  { value: 98,  suffix: "%", label: "Client Satisfaction", icon: "⭐" },
  { value: 15,  suffix: "+", label: "Countries Served",    icon: "🗺️" },
  { value: 40,  suffix: "+", label: "Team Members",        icon: "👥" },
];

export const TECH_STACK = [
  {
    label:       "Frontend",
    colorClass:  "text-[#2B7EC1]",
    borderClass: "border-[#2B7EC1]/20",
    bgClass:     "bg-[#2B7EC1]/5",
    techs:       ["React", "Next.js", "Vue 3", "TypeScript", "Tailwind CSS", "Framer Motion"],
  },
  {
    label:       "Mobile",
    colorClass:  "text-[#6B3FA0]",
    borderClass: "border-[#6B3FA0]/20",
    bgClass:     "bg-[#6B3FA0]/5",
    techs:       ["Flutter", "React Native", "Swift", "Kotlin", "Expo", "Firebase"],
  },
  {
    label:       "Backend",
    colorClass:  "text-[#00B4C8]",
    borderClass: "border-[#00B4C8]/20",
    bgClass:     "bg-[#00B4C8]/5",
    techs:       ["Node.js", "Python", "Django", "FastAPI", "Go", "GraphQL"],
  },
  {
    label:       "Database",
    colorClass:  "text-emerald-400",
    borderClass: "border-emerald-500/20",
    bgClass:     "bg-emerald-500/5",
    techs:       ["PostgreSQL", "MongoDB", "Redis", "Supabase", "Prisma", "MySQL"],
  },
  {
    label:       "Cloud & DevOps",
    colorClass:  "text-amber-400",
    borderClass: "border-amber-500/20",
    bgClass:     "bg-amber-500/5",
    techs:       ["AWS", "GCP", "Docker", "Kubernetes", "Vercel", "Terraform"],
  },
  {
    label:       "AI & Data",
    colorClass:  "text-pink-400",
    borderClass: "border-pink-500/20",
    bgClass:     "bg-pink-500/5",
    techs:       ["OpenAI API", "LangChain", "PyTorch", "Hugging Face", "Pinecone", "Pandas"],
  },
];

export const PROCESS_STEPS = [
  {
    number:       "01",
    title:        "Discovery & Scoping",
    description:  "We start with a deep-dive call to understand your goals, users, and constraints. Then we define scope, timelines, and success metrics.",
    duration:     "1–2 days",
    deliverables: ["Requirements Doc", "Project Scope", "Timeline & Milestones"],
    icon:         "🔍",
    accentColor:  "#2B7EC1",
  },
  {
    number:       "02",
    title:        "Design & Prototyping",
    description:  "Our designers create wireframes and interactive prototypes in Figma. You get full visibility and approval before a single line of code.",
    duration:     "3–7 days",
    deliverables: ["Wireframes", "UI Design System", "Clickable Prototype"],
    icon:         "🎨",
    accentColor:  "#6B3FA0",
  },
  {
    number:       "03",
    title:        "Development",
    description:  "Engineering sprints with daily standups and weekly demos. You have full access to staging throughout.",
    duration:     "2–12 weeks",
    deliverables: ["Staging Environment", "Weekly Demos", "Code Reviews"],
    icon:         "⚙️",
    accentColor:  "#00B4C8",
  },
  {
    number:       "04",
    title:        "QA & Testing",
    description:  "Rigorous testing across devices, browsers, and edge cases — automated test suites, performance audits, and accessibility checks.",
    duration:     "3–5 days",
    deliverables: ["QA Report", "Performance Audit", "Bug-free Staging"],
    icon:         "✅",
    accentColor:  "#10b981",
  },
  {
    number:       "05",
    title:        "Launch & Handoff",
    description:  "Zero-downtime deployment to production. Full code handoff with documentation. We train your team and ensure 100% confidence.",
    duration:     "1–2 days",
    deliverables: ["Production Deploy", "Documentation", "Team Training"],
    icon:         "🚀",
    accentColor:  "#f59e0b",
  },
  {
    number:       "06",
    title:        "Support & Growth",
    description:  "Post-launch retainer plans with SLA guarantees. We monitor, maintain, and continue iterating as your product grows.",
    duration:     "Ongoing",
    deliverables: ["SLA Monitoring", "Monthly Reports", "Roadmap Planning"],
    icon:         "🌱",
    accentColor:  "#ec4899",
  },
];

export const TESTIMONIALS = [
  {
    id:       1,
    name:     "Arjun Mehta",
    role:     "CEO, FinEdge Solutions",
    company:  "FinEdge Solutions",
    avatar:   "AM",
    color:    "bg-[#2B7EC1]/20 text-[#79b8f0]",
    rating:   5,
    project:  "Fintech Dashboard",
    text:     "TriAxon delivered our fintech dashboard in 6 weeks — well within budget and beyond expectations. We saw a 40% increase in user engagement after launch. Their attention to performance and security was exceptional.",
    location: "London, UK",
  },
  {
    id:       2,
    name:     "Sarah Williams",
    role:     "Product Manager, LogiFlow UK",
    company:  "LogiFlow",
    avatar:   "SW",
    color:    "bg-[#6B3FA0]/20 text-[#b392d8]",
    rating:   5,
    project:  "Logistics Mobile App",
    text:     "The mobile app they built handles 50,000+ daily active users flawlessly. Their Flutter expertise and proactive communication made the entire development process smooth and stress-free.",
    location: "Manchester, UK",
  },
  {
    id:       3,
    name:     "Priya Sharma",
    role:     "CTO, HealthBridge India",
    company:  "HealthBridge",
    avatar:   "PS",
    color:    "bg-[#00B4C8]/20 text-[#00B4C8]",
    rating:   5,
    project:  "Telemedicine Platform",
    text:     "We needed a HIPAA-compliant telemedicine platform with AI features in a tight timeline. TriAxon not only delivered on time but also integrated an AI symptom checker that our doctors love.",
    location: "Mumbai, India",
  },
  {
    id:       4,
    name:     "David Chen",
    role:     "Founder, EduTrack",
    company:  "EduTrack",
    avatar:   "DC",
    color:    "bg-emerald-500/20 text-emerald-400",
    rating:   5,
    project:  "EdTech Platform Migration",
    text:     "Outstanding technical expertise. They rebuilt our legacy PHP system into a modern Next.js platform. Page load times dropped from 8 seconds to under 1.2 seconds. Incredible outcome.",
    location: "Singapore",
  },
  {
    id:       5,
    name:     "Fatima Al-Rashid",
    role:     "VP Engineering, RetailMax",
    company:  "RetailMax",
    avatar:   "FA",
    color:    "bg-amber-500/20 text-amber-400",
    rating:   5,
    project:  "E-commerce Platform",
    text:     "TriAxon became a true partner. They proactively suggested improvements, flagged potential issues early, and delivered a robust e-commerce platform that scaled to Black Friday traffic.",
    location: "Dubai, UAE",
  },
];

export const PORTFOLIO_PROJECTS = [
  {
    slug:     "finedge-dashboard",
    title:    "FinEdge Dashboard",
    category: "Web App",
    industry: "Fintech",
    emoji:    "📈",
    result:   "40% engagement ↑",
    stack:    ["Next.js", "Python", "PostgreSQL"],
    duration: "14 weeks",
    featured: true,
  },
  {
    slug:     "logiflow-mobile",
    title:    "LogiFlow Mobile",
    category: "Mobile",
    industry: "Logistics",
    emoji:    "🚚",
    result:   "50K+ DAU",
    stack:    ["Flutter", "Node.js", "Firebase"],
    duration: "18 weeks",
    featured: true,
  },
  {
    slug:     "healthbridge-ai",
    title:    "HealthBridge AI",
    category: "AI/ML",
    industry: "HealthTech",
    emoji:    "🏥",
    result:   "92% AI Accuracy",
    stack:    ["Python", "FastAPI", "OpenAI", "React"],
    duration: "22 weeks",
    featured: true,
  },
  {
    slug:     "edutrack-lms",
    title:    "EduTrack LMS",
    category: "Web App",
    industry: "EdTech",
    emoji:    "📚",
    result:   "7× faster loads",
    stack:    ["Next.js", "Supabase", "Stripe"],
    duration: "10 weeks",
    featured: false,
  },
  {
    slug:     "retailmax-commerce",
    title:    "RetailMax Commerce",
    category: "Enterprise",
    industry: "Retail",
    emoji:    "🛒",
    result:   "$5M+ GMV",
    stack:    ["React", "Node.js", "AWS", "Redis"],
    duration: "28 weeks",
    featured: true,
  },
  {
    slug:     "smarthr-automator",
    title:    "SmartHR Automator",
    category: "AI/ML",
    industry: "HRTech",
    emoji:    "👥",
    result:   "60% faster onboarding",
    stack:    ["Vue 3", "Django", "GPT-4"],
    duration: "16 weeks",
    featured: false,
  },
];

export const BLOG_POSTS = [
  {
    slug:     "trpc-nextjs-app-router",
    title:    "Why We Moved All Client Projects from REST to tRPC + Next.js App Router",
    category: "Development",
    excerpt:  "After 12+ projects, we made the full switch. Here's what we learned — including surprising performance wins.",
    author:   { name: "Rahul Verma", role: "CTO",               avatar: "RV" },
    date:     "2025-04-28",
    readTime: "7 min read",
    emoji:    "⚛️",
    featured: true,
  },
  {
    slug:     "flutter-vs-react-native-2025",
    title:    "Flutter vs React Native in 2025: A Decision Framework for Startups",
    category: "Mobile",
    excerpt:  "We've shipped 20+ mobile apps. This is the honest, framework-agnostic guide — with real benchmarks.",
    author:   { name: "Karan Singh", role: "Head of Engineering", avatar: "KS" },
    date:     "2025-04-15",
    readTime: "9 min read",
    emoji:    "📱",
    featured: false,
  },
  {
    slug:     "rag-production-lessons",
    title:    "Building Production RAG Pipelines: Lessons from 5 Deployments",
    category: "AI/ML",
    excerpt:  "RAG sounds simple in demos. In production, it's a different story.",
    author:   { name: "Priya Joshi", role: "Head of AI/ML",      avatar: "PJ" },
    date:     "2025-03-30",
    readTime: "11 min read",
    emoji:    "🤖",
    featured: false,
  },
];

export const DEPARTMENTS = [
  "All", "Engineering", "Mobile", "AI", "Design", "Infrastructure", "Delivery",
];

export const BENEFITS = [
  { icon: "💰", title: "Competitive Salary",   desc: "Market-leading pay benchmarked against top Indian product companies." },
  { icon: "📈", title: "Performance Bonus",    desc: "Quarterly bonuses tied to project success and client satisfaction."   },
  { icon: "🏠", title: "Flexible Work",        desc: "Hybrid and remote options for most roles. We trust adults."           },
  { icon: "🎓", title: "₹30K Learning Budget", desc: "Courses, conferences, books, and certifications — yours to spend."   },
  { icon: "🏥", title: "Health Insurance",     desc: "Comprehensive cover for you and your family (₹5L sum insured)."       },
  { icon: "🌴", title: "25 Days Leave",        desc: "12 casual + 10 sick + 3 personal days. No questions asked."          },
  { icon: "💻", title: "MacBook Pro M3",       desc: "Latest MacBook Pro or equivalent Linux workstation — your choice."   },
  { icon: "🚀", title: "Career Growth",        desc: "Clear promotion tracks, annual reviews, and internal mobility."      },
];

export const BUDGET_OPTIONS = [
  { label: "< ₹1 Lakh",    value: "under-1l", usd: "< $1,200"    },
  { label: "₹1L – ₹5L",   value: "1l-5l",    usd: "$1.2K–$6K"   },
  { label: "₹5L – ₹20L",  value: "5l-20l",   usd: "$6K–$24K"    },
  { label: "₹20L – ₹50L", value: "20l-50l",  usd: "$24K–$60K"   },
  { label: "₹50L+",        value: "50l-plus", usd: "$60K+"       },
  { label: "Not sure yet", value: "unsure",   usd: "Not sure yet" },
];

export const TIMELINE_OPTIONS = [
  "ASAP (< 1 month)",
  "1–3 months",
  "3–6 months",
  "6+ months",
  "Flexible",
];

export const AWARDS = [
  { label: "Clutch Top B2B Company",   year: "2023", emoji: "🏆" },
  { label: "GoodFirms Top Developer",  year: "2023", emoji: "🏅" },
  { label: "NASSCOM Emerging 50",      year: "2022", emoji: "🌟" },
  { label: "Startup India Recognised", year: "2021", emoji: "🇮🇳" },
];

export const ANIMATION = {
  fast:     150,
  normal:   300,
  slow:     600,
  verySlow: 1000,
  countUp:  1800,
  stagger:  80,
  reveal:   700,
};

export const BREAKPOINTS = {
  sm:    640,
  md:    768,
  lg:    1024,
  xl:    1280,
  "2xl": 1536,
};

export const ROUTES = {
  home:              "/",
  about:             "/about",
  services:          "/services",
  servicesFullstack: "/services/fullstack",
  servicesAppDev:    "/services/app-development",
  servicesUiUx:      "/services/ui-ux-design",
  servicesCloud:     "/services/cloud-devops",
  servicesAiMl:      "/services/ai-ml",
  servicesMarketing: "/services/digital-marketing",
  portfolio:         "/portfolio",
  blog:              "/blog",
  careers:           "/careers",
  contact:           "/contact",
  privacy:           "/privacy",
  terms:             "/terms",
};

export const INTEGRATIONS = {
  googleAnalyticsId:  process.env.NEXT_PUBLIC_GA_ID        ?? "",
  googleTagManagerId: process.env.NEXT_PUBLIC_GTM_ID       ?? "",
  hotjarId:           process.env.NEXT_PUBLIC_HOTJAR_ID    ?? "",
  crispWebsiteId:     process.env.NEXT_PUBLIC_CRISP_ID     ?? "",
  formspreeEndpoint:  process.env.NEXT_PUBLIC_FORMSPREE_ID ?? "",
  calComLink:         "https://cal.com/triaxon/30min",
};